<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Update Data</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Untitled Form</a></h1>
						
				<?php

				$servername = "localhost";
				$username = "root";
				$password = "";
				$dbname = "ite298_nieto";

				// Create connection
				$conn = new mysqli($servername, $username, $password, $dbname);
				// Check connection
				if ($conn->connect_error) {
				  die("Connection failed: " . $conn->connect_error);
				}

				$id = $_GET['id']; // get id through query string

				$qry = mysqli_query($conn,"select * from studentinfo_nieto where id='$id'"); // select query

				$row = mysqli_fetch_array($qry);

				?>

		<form id="form_45636" class="appnitro"  method="GET" action="EditValidation.php" >
					<div class="form_description">
			<h2>Update Data</h2> 
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Full name </label>
		<span>
		
			<input id="element_1_1" name= "id" type="hidden" class="element text" maxlength="255" size="8" value="<?php echo $row["id"]?>"/>
			
			<input id="element_1_1" name= "Firstname" class="element text" maxlength="255"   value="<?php echo $row["firstname"]?>"/>
			<label>First</label>
		</span>
		<span>
			<input id="element_1_2" name= "Lastname" class="element text" maxlength="255"   value="<?php echo $row["lastname"]?>"/>
			<label>Last</label>
		</span> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Section </label>
		<div>
			<input id="element_2" name="Section" class="element text medium" type="text" maxlength="255" value="<?php echo $row["section"]?>"/> 
		</div> 
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Year </label>
		<div>
			<input id="element_3" name="Year" class="element text medium" type="text" maxlength="255" value="<?php echo $row["year"]?>"/> 
		</div> 
		</li>		<li id="li_4" >
		<label class="description" for="element_4">Address </label>
		<div>
			<input id="element_4" name="Address" class="element text medium" type="text" maxlength="255" value="<?php echo $row["address"]?>"/> 
		</div> 
		</li>		<li id="li_5" >
		<label class="description" for="element_5">Motto </label>
		<div>
			<input id="element_5" name="Motto" class="element text medium" type="text" maxlength="255" value="<?php echo $row["motto"]?>"/> 
		</div> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="45636" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>