<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert Data using SQL</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Insert Data using SQL</a></h1>
		<form id="form_45548" class="appnitro"  method="post" action="insertsql.php">
					<div class="form_description">
			<h2>Insert Data</h2>
		 
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">ID </label>
		<span>
			<input id="element_1_0" name= "id" class="element text" maxlength="255" size="30" value=""/>
			<label>ID</label>
		</span>
	</li>
		<li id="li_1" >
		<label class="description" for="element_1">Name </label>
		<span>
			<input id="element_1_1" name= "firstname" class="element text" maxlength="255" size="30" value=""/>
			<label>FirstName</label>
		</span>
		<span>
			<input id="element_1_2" name= "lastname" class="element text" maxlength="255" size="30" value=""/>
			<label>LastName</label>
		</span>
	</li>
	<li id="li_1" >
		<label class="description" for="element_1">Section </label>
			<span>
			<input id="element_1_3" name= "section" class="element text" maxlength="255" size="30" value=""/>
			<label>Section</label>
		</span></li>
		<li id="li_1" >
		<label class="description" for="element_1">Year </label>
		<span>
			<input id="element_1_4" name= "year" class="element text" maxlength="255" size="30" value=""/>
			<label>Year</label>
		</span>
	</li>
		<li id="li_1" >
		<label class="description" for="element_1">Address </label>
		<span>
			<input id="element_1_5" name= "address" class="element text" maxlength="255" size="30" value=""/>
			<label>Address</label>
		</span>
	</li>
		<li id="li_1" >
		<label class="description" for="element_1">Motto </label>
		<span>
			<input id="element_1_6" name= "motto" class="element text" maxlength="255" size="30" value=""/>
			<label>Motto</label>
		</span>  
		</li>		
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="45548" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>

	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>